### ISSUE TITLE
Minor Setup Issues with 2FA and Master Password

### ISSUE THREAD

**Issue by calipet-tech** [rguisewite/MvSublimeTemplateEditor#1]
I was experimenting with this plugin, and I am running into some issues. 

**Environment**

- Miva Version: 9.14
- Sublime Version: 3.2.2 build 3211
- Openssl: 1.1.1d

**Issues**

- Master Password
    - When this was enabled and I would ask for the templates, it would say 
      > Master password not set. Press Enter to set password.
    - After pressing `enter` I'd enter a password, into the field that popped up from the bottom of my Sublime window, expecting it to be added
    - the response was
       > Wrong password.
    - This is likely a gap in user knowledge, but I didn't see any where to set this up in the readme or config.
- 2FA
    - After disabling the Master Password a connection to our store was made
    - Then a dialog popped up saying 
       > This account requires two-factor authentication
    - and closed the window and the connection

**Things I tried**

- I tried creating a new general user, setup as a "developer" and when I tried to login the system responded with the following
   > error: Your administrative session has timed out.  Please re-login to continue.

**Thoughts**

It looks like this tool isn't being very actively worked on, last commit was in May 2017. Is this tool still something that you are keeping up? Would these issues be resolved? 
It's totally fine if you're not going to work on it anymore, We just want to know what to expect.

**Comment by rguisewite** [comment]
I've thought about rewriting this plugin a few times, because... as it stands, getting it to work with all of our semi-recent authentication changes to Miva Merchant, requires some downgrades in security on your store (never optimal). The problem is that it is likely going to be a full or nearly full rewrite and I just haven't really had the time or resources to throw at it. 

For the master password problems, I'd look at your openssl setup and make sure it's working correctly. If you're on windows, I think you have to download the openssl binary and put it somewhere sublime will have access to, then set the correct path in the package's settings. If you're on a mac, either use the version macOS comes with, or brew install a specific version and set the package setting's path to that. You should be able to tell if it is working because the passwords stored in the package's User settings file will show an encrypted password (vs plain text).

For 2FA, Administrator and Developer (license) accounts must have 2FA enabled on their account (this is a requirement within Miva Merchant). You can create a normal account and assign them to a user group with the PAGE privilege enabled (View, Add, and Modify).

(Sorry, I just accidentally clicked the close button).

Anyway, I originally wrote this plugin as an "I wonder how easy it would be" type of thing. I don't actually use this plugin, nor have I really put any work into it in the past few years. Some changes coming down the line in future releases of Miva Merchant will (hopefully) make this plugin obsolete/unnecessary. If that is not the case, it is likely I will revisit this plugin and update it to utilize some of the newer features and functionality (like the API) so that the need to turn off some of the protective measures on your account will no longer be necessary

**Comment by calipet-tech** [comment]
Appreciate the follow up @rguisewite!

We're excited to see what the Miva platform and API allows us and you to do.
